name: parkx
description: Parkx

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+22

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.3
  http: ^1.2.1
  flutter_flavor: ^3.1.3
  flutter_secure_storage: ^9.0.0
  carousel_slider: ^5.0.0
  email_validator: ^2.1.16
  flutter_pw_validator: ^1.6.0
  pin_code_fields: ^8.0.1
  otp_timer_button: ^1.1.1
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.13.1
  intl: any
  flutter_multi_formatter: ^2.12.8
  flutter_widget_from_html: ^0.15.0
  credit_card_validator: ^2.1.0
  loader_overlay: ^5.0.0
  meta: ^1.11.0
  url_launcher: ^6.3.1
  url_launcher_ios: ^6.3.2
  flutter_stripe: ^11.0.0
  win32: ^5.10.0
  dio: ^5.4.0
  mobile_scanner: ^7.0.0
  permission_handler: ^12.0.0+1
  dropdown_button2: ^2.3.9
  sentry_flutter: ^8.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: Sansation
      fonts:
        - asset: assets/fonts/Sansation/Sansation_Bold_Italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Sansation/Sansation_Bold.ttf
          weight: 700
        - asset: assets/fonts/Sansation/Sansation_Regular.ttf
          weight: 300
        - asset: assets/fonts/Sansation/Sansation_Italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Sansation/Sansation_Light.ttf
          weight: 200
        - asset: assets/fonts/Sansation/Sansation_Light_Italic.ttf
          weight: 200
          style: italic
    - family: Signika SC
      fonts:
        - asset: assets/fonts/SignikaSC/SignikaSC[wght].ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 100
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 800
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
